export const ADD_TO_BREAKFAST = 'ADD_TO_BREAKFAST'
export const REMOVE_FROM_BREAKFAST = 'REMOVE_FROM_BREAKFAST'

export const ADD_TO_BREAKFAST_YESTERDAY = 'ADD_TO_BREAKFAST_YESTERDAY'
export const ADD_TO_COLLATION1_YESTERDAY = 'ADD_TO_COLLATION1_YESTERDAY'
export const ADD_TO_LUNCH_YESTERDAY = 'ADD_TO_LUNCH_YESTERDAY'
export const ADD_TO_COLLATION2_YESTERDAY = 'ADD_TO_COLLATION2_YESTERDAY'
export const ADD_TO_DINNER_YESTERDAY = 'ADD_TO_DINNER_YESTERDAY'

export const INCREASE_COUNT = 'INCREASE_COUNT'
export const DECREASE_COUNT = 'DECREASE_COUNT'

export const ADD_TIME = 'ADD_TIME'
export const ADD_WATER = 'ADD_WATER'